# fly.toml app configuration file generated for omarstore on 2023-07-26T14:13:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "omarstore"
primary_region = "lhr"

[build]
  image = "omartayeh/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dtx22hi0o"
  Cloudinary__ApiKey="449347364855319"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
